// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2025, 00:33:57
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/common/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/layout/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/auth/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/property/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/booking/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/payment/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/review/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/user/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/components/message/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/plugins/**/*.{js,ts,mjs}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/composables/**/*.{js,ts,mjs}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/utils/**/*.{js,ts,mjs}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/OneDrive/Escritorio/EnLaCeiba/client/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;