
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BreadcrumbNav': typeof import("../components/BreadcrumbNav.vue")['default']
    'PriceDisplay': typeof import("../components/PriceDisplay.vue")['default']
    'PriceSlider': typeof import("../components/PriceSlider.vue")['default']
    'PropertyDetailsSidebar': typeof import("../components/PropertyDetailsSidebar.vue")['default']
    'PropertyFavoriteButton': typeof import("../components/PropertyFavoriteButton.vue")['default']
    'PropertyFilterSidebar': typeof import("../components/PropertyFilterSidebar.vue")['default']
    'PropertyGallery': typeof import("../components/PropertyGallery.vue")['default']
    'PropertyMainInfo': typeof import("../components/PropertyMainInfo.vue")['default']
    'PropertyMap': typeof import("../components/PropertyMap.vue")['default']
    'RecentlyViewed': typeof import("../components/RecentlyViewed.vue")['default']
    'AboutBreadcrumb': typeof import("../components/about/Breadcrumb.vue")['default']
    'AboutMain': typeof import("../components/about/main.vue")['default']
    'AboutReviews': typeof import("../components/about/reviews.vue")['default']
    'AboutTeam': typeof import("../components/about/team.vue")['default']
    'DashboardCard': typeof import("../components/dashboard/DashboardCard.vue")['default']
    'HomeAgents': typeof import("../components/home/Agents.vue")['default']
    'HomeCallToAction': typeof import("../components/home/CallToAction.vue")['default']
    'HomeCategories': typeof import("../components/home/Categories.vue")['default']
    'HomeCategoryBox': typeof import("../components/home/CategoryBox.vue")['default']
    'HomeCities': typeof import("../components/home/Cities.vue")['default']
    'HomeConstCalculator': typeof import("../components/home/ConstCalculator.vue")['default']
    'HomeFeaturedProperties': typeof import("../components/home/FeaturedProperties.vue")['default']
    'HomeHero': typeof import("../components/home/Hero.vue")['default']
    'HomeOffers': typeof import("../components/home/Offers.vue")['default']
    'HomePartners': typeof import("../components/home/Partners.vue")['default']
    'HomeRecentlyAdded': typeof import("../components/home/RecentlyAdded.vue")['default']
    'HomeSearchBox': typeof import("../components/home/SearchBox.vue")['default']
    'HomeServices': typeof import("../components/home/Services.vue")['default']
    'HomeTestimonials': typeof import("../components/home/Testimonials.vue")['default']
    'LayoutAppFooter': typeof import("../components/layout/AppFooter.vue")['default']
    'LayoutAppHeader': typeof import("../components/layout/AppHeader.vue")['default']
    'LayoutAuthModals': typeof import("../components/layout/AuthModals.vue")['default']
    'LayoutCustom 404': typeof import("../components/layout/Custom 404.vue")['default']
    'PropertyCard': typeof import("../components/property/PropertyCard.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBreadcrumbNav': typeof import("../components/BreadcrumbNav.vue")['default']
    'LazyPriceDisplay': typeof import("../components/PriceDisplay.vue")['default']
    'LazyPriceSlider': typeof import("../components/PriceSlider.vue")['default']
    'LazyPropertyDetailsSidebar': typeof import("../components/PropertyDetailsSidebar.vue")['default']
    'LazyPropertyFavoriteButton': typeof import("../components/PropertyFavoriteButton.vue")['default']
    'LazyPropertyFilterSidebar': typeof import("../components/PropertyFilterSidebar.vue")['default']
    'LazyPropertyGallery': typeof import("../components/PropertyGallery.vue")['default']
    'LazyPropertyMainInfo': typeof import("../components/PropertyMainInfo.vue")['default']
    'LazyPropertyMap': typeof import("../components/PropertyMap.vue")['default']
    'LazyRecentlyViewed': typeof import("../components/RecentlyViewed.vue")['default']
    'LazyAboutBreadcrumb': typeof import("../components/about/Breadcrumb.vue")['default']
    'LazyAboutMain': typeof import("../components/about/main.vue")['default']
    'LazyAboutReviews': typeof import("../components/about/reviews.vue")['default']
    'LazyAboutTeam': typeof import("../components/about/team.vue")['default']
    'LazyDashboardCard': typeof import("../components/dashboard/DashboardCard.vue")['default']
    'LazyHomeAgents': typeof import("../components/home/Agents.vue")['default']
    'LazyHomeCallToAction': typeof import("../components/home/CallToAction.vue")['default']
    'LazyHomeCategories': typeof import("../components/home/Categories.vue")['default']
    'LazyHomeCategoryBox': typeof import("../components/home/CategoryBox.vue")['default']
    'LazyHomeCities': typeof import("../components/home/Cities.vue")['default']
    'LazyHomeConstCalculator': typeof import("../components/home/ConstCalculator.vue")['default']
    'LazyHomeFeaturedProperties': typeof import("../components/home/FeaturedProperties.vue")['default']
    'LazyHomeHero': typeof import("../components/home/Hero.vue")['default']
    'LazyHomeOffers': typeof import("../components/home/Offers.vue")['default']
    'LazyHomePartners': typeof import("../components/home/Partners.vue")['default']
    'LazyHomeRecentlyAdded': typeof import("../components/home/RecentlyAdded.vue")['default']
    'LazyHomeSearchBox': typeof import("../components/home/SearchBox.vue")['default']
    'LazyHomeServices': typeof import("../components/home/Services.vue")['default']
    'LazyHomeTestimonials': typeof import("../components/home/Testimonials.vue")['default']
    'LazyLayoutAppFooter': typeof import("../components/layout/AppFooter.vue")['default']
    'LazyLayoutAppHeader': typeof import("../components/layout/AppHeader.vue")['default']
    'LazyLayoutAuthModals': typeof import("../components/layout/AuthModals.vue")['default']
    'LazyLayoutCustom 404': typeof import("../components/layout/Custom 404.vue")['default']
    'LazyPropertyCard': typeof import("../components/property/PropertyCard.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BreadcrumbNav: typeof import("../components/BreadcrumbNav.vue")['default']
export const PriceDisplay: typeof import("../components/PriceDisplay.vue")['default']
export const PriceSlider: typeof import("../components/PriceSlider.vue")['default']
export const PropertyDetailsSidebar: typeof import("../components/PropertyDetailsSidebar.vue")['default']
export const PropertyFavoriteButton: typeof import("../components/PropertyFavoriteButton.vue")['default']
export const PropertyFilterSidebar: typeof import("../components/PropertyFilterSidebar.vue")['default']
export const PropertyGallery: typeof import("../components/PropertyGallery.vue")['default']
export const PropertyMainInfo: typeof import("../components/PropertyMainInfo.vue")['default']
export const PropertyMap: typeof import("../components/PropertyMap.vue")['default']
export const RecentlyViewed: typeof import("../components/RecentlyViewed.vue")['default']
export const AboutBreadcrumb: typeof import("../components/about/Breadcrumb.vue")['default']
export const AboutMain: typeof import("../components/about/main.vue")['default']
export const AboutReviews: typeof import("../components/about/reviews.vue")['default']
export const AboutTeam: typeof import("../components/about/team.vue")['default']
export const DashboardCard: typeof import("../components/dashboard/DashboardCard.vue")['default']
export const HomeAgents: typeof import("../components/home/Agents.vue")['default']
export const HomeCallToAction: typeof import("../components/home/CallToAction.vue")['default']
export const HomeCategories: typeof import("../components/home/Categories.vue")['default']
export const HomeCategoryBox: typeof import("../components/home/CategoryBox.vue")['default']
export const HomeCities: typeof import("../components/home/Cities.vue")['default']
export const HomeConstCalculator: typeof import("../components/home/ConstCalculator.vue")['default']
export const HomeFeaturedProperties: typeof import("../components/home/FeaturedProperties.vue")['default']
export const HomeHero: typeof import("../components/home/Hero.vue")['default']
export const HomeOffers: typeof import("../components/home/Offers.vue")['default']
export const HomePartners: typeof import("../components/home/Partners.vue")['default']
export const HomeRecentlyAdded: typeof import("../components/home/RecentlyAdded.vue")['default']
export const HomeSearchBox: typeof import("../components/home/SearchBox.vue")['default']
export const HomeServices: typeof import("../components/home/Services.vue")['default']
export const HomeTestimonials: typeof import("../components/home/Testimonials.vue")['default']
export const LayoutAppFooter: typeof import("../components/layout/AppFooter.vue")['default']
export const LayoutAppHeader: typeof import("../components/layout/AppHeader.vue")['default']
export const LayoutAuthModals: typeof import("../components/layout/AuthModals.vue")['default']
export const LayoutCustom 404: typeof import("../components/layout/Custom 404.vue")['default']
export const PropertyCard: typeof import("../components/property/PropertyCard.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBreadcrumbNav: typeof import("../components/BreadcrumbNav.vue")['default']
export const LazyPriceDisplay: typeof import("../components/PriceDisplay.vue")['default']
export const LazyPriceSlider: typeof import("../components/PriceSlider.vue")['default']
export const LazyPropertyDetailsSidebar: typeof import("../components/PropertyDetailsSidebar.vue")['default']
export const LazyPropertyFavoriteButton: typeof import("../components/PropertyFavoriteButton.vue")['default']
export const LazyPropertyFilterSidebar: typeof import("../components/PropertyFilterSidebar.vue")['default']
export const LazyPropertyGallery: typeof import("../components/PropertyGallery.vue")['default']
export const LazyPropertyMainInfo: typeof import("../components/PropertyMainInfo.vue")['default']
export const LazyPropertyMap: typeof import("../components/PropertyMap.vue")['default']
export const LazyRecentlyViewed: typeof import("../components/RecentlyViewed.vue")['default']
export const LazyAboutBreadcrumb: typeof import("../components/about/Breadcrumb.vue")['default']
export const LazyAboutMain: typeof import("../components/about/main.vue")['default']
export const LazyAboutReviews: typeof import("../components/about/reviews.vue")['default']
export const LazyAboutTeam: typeof import("../components/about/team.vue")['default']
export const LazyDashboardCard: typeof import("../components/dashboard/DashboardCard.vue")['default']
export const LazyHomeAgents: typeof import("../components/home/Agents.vue")['default']
export const LazyHomeCallToAction: typeof import("../components/home/CallToAction.vue")['default']
export const LazyHomeCategories: typeof import("../components/home/Categories.vue")['default']
export const LazyHomeCategoryBox: typeof import("../components/home/CategoryBox.vue")['default']
export const LazyHomeCities: typeof import("../components/home/Cities.vue")['default']
export const LazyHomeConstCalculator: typeof import("../components/home/ConstCalculator.vue")['default']
export const LazyHomeFeaturedProperties: typeof import("../components/home/FeaturedProperties.vue")['default']
export const LazyHomeHero: typeof import("../components/home/Hero.vue")['default']
export const LazyHomeOffers: typeof import("../components/home/Offers.vue")['default']
export const LazyHomePartners: typeof import("../components/home/Partners.vue")['default']
export const LazyHomeRecentlyAdded: typeof import("../components/home/RecentlyAdded.vue")['default']
export const LazyHomeSearchBox: typeof import("../components/home/SearchBox.vue")['default']
export const LazyHomeServices: typeof import("../components/home/Services.vue")['default']
export const LazyHomeTestimonials: typeof import("../components/home/Testimonials.vue")['default']
export const LazyLayoutAppFooter: typeof import("../components/layout/AppFooter.vue")['default']
export const LazyLayoutAppHeader: typeof import("../components/layout/AppHeader.vue")['default']
export const LazyLayoutAuthModals: typeof import("../components/layout/AuthModals.vue")['default']
export const LazyLayoutCustom 404: typeof import("../components/layout/Custom 404.vue")['default']
export const LazyPropertyCard: typeof import("../components/property/PropertyCard.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
